#!/bin/bash


for file in "$@"
do
	# Store number of lines using wc (man wc) or cut and take field 1 of the last line 
	lines=`wc -l < $file` 
	#lines=`cat -n $file | tr -s " " | cut -f1 |tail -1`
	#echo "LINES" $lines
	
	# Numeric sort of file and take the biggest (stored at the tail)
	maxNum=`sort -n $file | tail -1`
	#echo "max" $maxNum

	#Numeric sort of file and take the smaller (stored at the head)
	minNum=`sort -n $file | head -1`
	#echo "min" $minNum

	printf "FILE:%s, lines:%d, max=%s, min=%s\n" $file $lines $maxNum $minNum
done

